### ISSUE TITLE
Пора!

### ISSUE THREAD

**Issue by wldmr-key** [vanlos/sapr71-bank#1]
пора бы что-то написать ))

**Comment by vanlos** [comment]
Я поговорил с Вершининым, и он посоветовал мне сменить тему. Я переделаю тз и пришлю. Теперь тема будет про информационный банковский портал.

**Comment by wldmr-key** [comment]
ок, запасаюсь попкорном ))

**Comment by vanlos** [comment]
[TZ.docx](https://github.com/vanlos/sapr71-bank/files/5316728/TZ.docx)

**Comment by wldmr-key** [comment]
назначение разработки точно оттуда? ))

**Comment by vanlos** [comment]
[Issledovatelskaya.docx](https://github.com/vanlos/sapr71-bank/files/5360943/Issledovatelskaya.docx)

**Comment by wldmr-key** [comment]
`Это финансовое учреждение или компания, которые предлагают широкий спектр финансовых услуг в одном месте. ` - твой случай это супермаркет? Ты будешь предоставлять финансовые услуги? Или, все-таки, информационные?
Анализ предметной области (аналогов, впрочем, тоже) не дает явных ответов на вопросы, а чего хочет клиент. А, как я понимаю, главным спосором приложения служит именно он. Задача сайта привлечь максимум клиентов. А ты не говоришь, чем ты их привлечешь и не выкатываешь явной альтернативы банки.ру ( у него сплошные достоинства, хотя поиск по условиям явно неидеален, а модерация отзывов - не такой уж и недостаток)

**Comment by vanlos** [comment]
[Issledovatelskaya.docx](https://github.com/vanlos/sapr71-bank/files/5397315/Issledovatelskaya.docx)

**Comment by wldmr-key** [comment]
вывод из сравнения аналогов скромноват, ну да ладно. Я рассчитывал, что в результате сравнения ты сможешь конкретизировать требования к разрабатываемой системе

**Comment by vanlos** [comment]
[Issledovatelskaya.docx](https://github.com/vanlos/sapr71-bank/files/5464348/Issledovatelskaya.docx)

**Comment by wldmr-key** [comment]
Хорошо, что написал про скрейпер, но хотелось бы конкретики в том, что ты хочешь от него добиться. И это явно не относится к описанию предметной области. Стоило поставить задачи разработки, я думаю. Описать данные, с которыми будешь работать...
