### ISSUE TITLE
Конструкторская

### ISSUE THREAD

**Issue by vanlos** [vanlos/sapr71-bank#2]
Я смог написать скрейпер на питоне. Проблема оказалась в разных названиях классов html страниц, power shell показал мне настоящие.
Хочу уточнить: в пункте "Обработка информации" мне нужно описать работу скрейпера и хранение полученных данных?

**Comment by wldmr-key** [comment]
да, вполне!

**Comment by vanlos** [comment]
код скрейпера закоменчен полностью, можно просто скриншот вставить? а хранение уже опишу

**Comment by wldmr-key** [comment]
ну, глянем, как получается ))

**Comment by vanlos** [comment]
[konstruktorskaya.docx](https://github.com/vanlos/sapr71-bank/files/5577562/konstruktorskaya.docx)
Пока вот что. Принцип работы поиска и интерфейс добавлю позже

**Comment by wldmr-key** [comment]
нормально. Будешь освещать вопрос, как перенастраивать скрейпер при изменении ситуации?

**Comment by vanlos** [comment]
да в принципе там только классы менять надо под страницу. ну может это в руководство для обновлений в технологической добавить?

**Comment by wldmr-key** [comment]
да, именно так

**Comment by vanlos** [comment]
[konstruktorskaya.docx](https://github.com/vanlos/sapr71-bank/files/5612351/konstruktorskaya.docx)
Допилено

**Comment by wldmr-key** [comment]
пойдет...
