### ISSUE TITLE
Технологическая

### ISSUE THREAD

**Issue by vanlos** [vanlos/sapr71-bank#3]
[technologicheskaya.docx](https://github.com/vanlos/sapr71-bank/files/5647003/technologicheskaya.docx)
Маловато вышло.

**Comment by vanlos** [comment]
И проект еще загрузил

**Comment by wldmr-key** [comment]
вы совершенно напрасно переписываете Мишину фигню: "Для развертывания системы нужно развернуть ее. После этого пользователь начнет получать удовольствие" - очень познавательно, и, главное, для всех годится!!! 
Все так реально просто?! Может-таки нужны некоторые подробности?!

Сопровождение системы - тоже ниачем

Обновление - вот уже туда-сюда. Еще бы пример приложить - так вааще загляденьице будет!

4.3.2 - за гранью добра и зла ))

**Comment by vanlos** [comment]
4.1 -  я  же просто короткий порядок действий написал, я убирал не нужное. а так да, надо что то еще добавить.
4,2 - просто не знал что писать
4,3,1 - как привести пример? мне взять какую-нибудь страницу и написать как найти контейнеры в ней?
4,3,2- ну по факту это все, воду лить бессмысленно. можно слить с 4,3,1

**Comment by vanlos** [comment]
[technologicheskaya.docx](https://github.com/vanlos/sapr71-bank/files/5652448/technologicheskaya.docx)
Расписал пример добавления новой страницы

**Comment by wldmr-key** [comment]
нормально...

**Comment by vanlos** [comment]
Стоит ли что то добавить в "Сопровождение системы" или вообще убрать?
Что вообще еще можно добавить? 
Юнит-тесты можно написать для калькуляторов, но я вроде учел все возможные случаи ошибок

**Comment by wldmr-key** [comment]
> Стоит ли что то добавить в "Сопровождение системы" или вообще убрать?

вообще убрать

> Что вообще еще можно добавить?
> Юнит-тесты можно написать для калькуляторов, 

я бы их добавил - хоть, руку набьешь - пригодится

> но я учел все возможные случаи ошибок

хорошая фраза, я ее тоже всегда говорю ))

**Comment by vanlos** [comment]
[technologicheskaya.docx](https://github.com/vanlos/sapr71-bank/files/5665285/technologicheskaya.docx)
как то так

**Comment by vanlos** [comment]
[technologicheskaya.docx](https://github.com/vanlos/sapr71-bank/files/5683038/technologicheskaya.docx)
дописал

**Comment by wldmr-key** [comment]
тебе как будто за каждое слово по рублю недоплачивают! )) Выводы делать будем? Задачи выполнены/не выполнены, что еще можно/нужно сделать?

А так - нормально

**Comment by vanlos** [comment]
а что для мимапра стоит отделить?

**Comment by wldmr-key** [comment]
ну, уж, не технологическую часть, во всяком случае ))
Большую часть исследовательской. Мотивацию пользователя. Обоснование проектных решений (ну и технологических - типо для чего тесты нужны и куда двигаться дальше. И как)

**Comment by vanlos** [comment]
ТЗ точно такое же останется?
Мотивация пользователя использовать эту систему? это в какой пункт?
Обоснование проектных решений - это почему выбрал именно эти инструменты разработки?
В технологической оставить тесты и добавить перспективы развития системы?

**Comment by wldmr-key** [comment]
> ТЗ точно такое же останется?

ох, ну откуда ж я знаю требования к тому ТЗ? по сути, да, наверное

> Мотивация пользователя использовать эту систему? это в какой пункт?

исследование

> Обоснование проектных решений - это почему выбрал именно эти инструменты разработки?

конструкторская

> В технологической оставить тесты и добавить перспективы развития системы?

написать про методики тестирования, чтобы было не так похоже

Постарайся, чтобы тексты не производили впечатления копий
